
name: Windows CI

on:
  push:
    branches: 
      - master
      - develop
      - issue/**
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install NodeJS Dependencies
      run: yarn install

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Run Tests (Linux w/xvfb)
      run: xvfb-run -a npm test
      if: runner.os == 'Linux'

    - name: Run Tests (Windows/MacOS)
      run: npm test
      if: runner.os != 'Linux'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt

    - name: Run Python Tests (pytest)
      run: |
        pytest
